### ISSUE TITLE
multiple issues with test-server

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#9]
Related to https://github.com/phetsims/chipper/issues/478, but since test-server has moved to aqua, I'll open a new issue here.

There were significant changes to test-server query parameters and documentation, which I reviewed in https://github.com/phetsims/chipper/issues/478#issuecomment-252308113.  I did not (at the time) test drive the instructions. 

My test drive of master @481eb87de41a402b4d3c153a58ca2ca8290f66cc reveals the following issues ( `node aqua/test-server/test-server.js` running, Mac OS X 10.11.6, Chrome):

(1) test-server/README.md indicates that `testBuilt` defaults to true. But with http://localhost/~cmalley/GitHub/aqua/test-server/test-sims.html?ea, it built only the first sim (acid-base-solutions).  Here's the first part of the console output:

![screenshot_56](https://cloud.githubusercontent.com/assets/3046552/19521535/3f0743c2-95d1-11e6-8b04-c7c759d2bc1b.png)

(2) No boxes other than the first column were filled in:

![screenshot_55](https://cloud.githubusercontent.com/assets/3046552/19521401/c7edcc70-95d0-11e6-9ac3-bab64d5bca16.png)

(3) test-server/README.md does not indicate the default value for `testDuration`.

(4) If query parameters are passed through to all sims, then why do we need `testTask=fuzzMouse` and `testFuzzRate`.  Why can't we just specify (e.g.) `fuzzMouse=1000`?

**Comment by pixelzoom** [comment]
This documentation in README.md also looks incorrect:

```
* Left: run in require.js mode with fuzz test
* Middle: build
* Right: run the build version with fuzz test
```

Should "with fuzz test" be deleted? Or are these boxes only relevant if `testTask=fuzzMouse`?

**Comment by pixelzoom** [comment]
Hmmm... After a *long* while, the builds did start.   Is `testDuration` by any chance still keeping each sim open (for 30 seconds?) when there's no fuzzMouse being done?

**Comment by pixelzoom** [comment]
This looks odd:

![screenshot_57](https://cloud.githubusercontent.com/assets/3046552/19522676/475a9e76-95d5-11e6-9bf5-27b74dcc9a09.png)

area-model-multiplication was failing to build, but there's no error shown above.  When I attempted to build it from the command line, here's the error I saw:

```
grunt
module.js:338
    throw err;
    ^

Error: Cannot find module './lib/coffee-script/register'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/cmalley/PhET/GitHub/area-model-multiplication/node_modules/grunt/node_modules/coffee-script/register.js:1:63)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Is there something wrong with the display of errors?

**Comment by jonathanolson** [comment]
> (1) test-server/README.md indicates that testBuilt defaults to true. But with http://localhost/~cmalley/GitHub/aqua/test-server/test-sims.html?ea, it built only the first sim (acid-base-solutions). Here's the first part of the console output:
> area-model-multiplication was failing to build, but there's no error shown above. When I attempted to build it from the command line, here's the error I saw:

'npm update' and 'grunt' stderr will now be included in the output string, so hopefully this would be caught with an error message in the future.

> (2) No boxes other than the first column were filled in:

Presumably caused by the above.

> (3) test-server/README.md does not indicate the default value for testDuration.

Done, and updated all of the test-server/test-sims documentation.

> (4) If query parameters are passed through to all sims, then why do we need testTask=fuzzMouse and testFuzzRate. Why can't we just specify (e.g.) fuzzMouse=1000?

Very true! I removed testFuzzRate in the above task, and modified testTask to a boolean:

- True: Keeps the sim open after loading, to test whatever task was provided (e.g. fuzzMouse passed directly)
- False: Moves to the next sim immediately after the previous sim loads

> (5) This documentation in README.md looks incorrect:

Fixed in documentation update above.

> Hmmm... After a long while, the builds did start. Is testDuration by any chance still keeping each sim open (for 30 seconds?) when there's no fuzzMouse being done?

I'm not sure, let me know if you experience this more. Could have been caused by the build-style node failure above.

**Comment by jonathanolson** [comment]
@pixelzoom, can you at your convenience (next time you need to test things?) review the documentation and try running it again?

**Comment by pixelzoom** [comment]
I'm trying to confirm that all sims load in requirejs mode.  So (following the README) I'm running with `?testBuild=false&testTask=false` --- I'm still seeing sims being built. ?!?

**Comment by jonathanolson** [comment]
testBuilt not testBuild?

**Comment by pixelzoom** [comment]
Typo in my comment, not in my usage:
http://localhost/~cmalley/GitHub/aqua/test-server/test-sims.html?testBuild=false&testTask=false
I see sims being built, and built sims being run.

**Comment by pixelzoom** [comment]
Whoopsie, I did have the query parameter wrong, should be `?testBuilt`.

**Comment by pixelzoom** [comment]
@jonathanolson and I discussed separating 'build' and 'run build' into separate query parameters, but will do that when the need arises. 

Closing.
